name: space_x_app
description: Space X API project

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  build_runner: ^2.3.3
  dio: ^5.0.0
  intl: ^0.17.0
  dartx: ^1.1.0
  gap: ^2.0.1
  sentry_flutter: ^6.20.1
  stacked: ^3.1.0+3
  stacked_themes: ^0.3.9
  shared_preferences: ^2.0.17
  stacked_generator: ^0.9.1+1
  flutter_svg: ^2.0.1
  fluttertoast: ^8.2.1
  json_serializable: ^6.6.1
  json_annotation: ^4.8.0
  retrofit_generator: ^5.0.0
  shimmer: ^2.0.0
  url_launcher: ^6.1.9
  responsive_framework: ^0.2.0
  retrofit: ^4.0.1
  firebase_remote_config: ^3.0.12
  firebase_crashlytics: ^3.0.14
  local_auth: ^2.1.3
  firebase_messaging: ^14.2.4
  phrase: ^1.1.0
  package_info_plus: ^1.4.3+1
  firebase_analytics: ^10.1.3
  firebase_core: ^2.6.1
  version: ^3.0.2
  permission_handler: ^10.2.0
  app_settings: ^4.2.0
  stacked_services: ^0.9.9
  pin_code_fields: ^7.4.0
  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/svg/


  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
